INSERT INTO Categories(Name, isActive) VALUES
('Fiction', 1),
('Non-fiction', 1),
('Science Fiction', 1),
('Mystery', 1),
('Thriller', 1),
('Horror', 1),
('Romance', 1),
('Fantasy', 1),
('Historical Fiction', 1),
('Biography', 1),
('Memoir', 1),
('Self-help', 1),
('Cookbook', 1),
('Travel', 1),
('Poetry', 1),
('Art', 1),
('Music', 1),
('History', 1),
('Science', 1),
('Mathematics', 1),
('Philosophy', 1),
('Religion', 1),
('Business', 1),
('Economics', 1),
('Psychology', 1),
('Sociology', 1),
('Education', 1),
('Technology', 1),
('Computer Science', 1),
('Health', 1);